version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    deploy:
      replicas: 1 # Defaults to 1, but we're being explicit
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - flask-app
  flask-app:
    image: stratcastor/flask-app:latest
    build: ./
    deploy:
      replicas: 3